CREATE DATABASE Qlybanhang
GO
USE Qlybanhang
CREATE TABLE CUSTOMERS(
	CUS_ID BIGINT PRIMARY KEY IDENTITY,
	CUSTOMERNAME NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NULL,
	PHONE NVARCHAR(20) NULL,
	EMAIL NVARCHAR(50) NULL	 
)

CREATE TABLE SUPPLIERS(
	SUP_ID BIGINT PRIMARY KEY IDENTITY,
	SUPPLIERNAME NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NULL,
	PHONE NVARCHAR(20) NULL
 )

CREATE TABLE RECEIPTS(
	REC_ID BIGINT PRIMARY KEY IDENTITY,
	CUS_ID BIGINT NOT NULL,
	RECEIPTDATE	DATETIME	NULL	DEFAULT GETDATE()
)

CREATE TABLE PRODUCTS(
	PRO_ID BIGINT PRIMARY KEY IDENTITY,
	SUP_ID BIGINT NOT NULL,
	PRODUCTCODE	NVARCHAR(20)	NOT NULL,
	PRODUCTNAME	NVARCHAR(50)	NOT NULL,
	PRICE	MONEY	NOT NULL	CHECK (PRICE>=0)
 )
 
CREATE TABLE RECEIPTITEMS(
	REI_ID BIGINT PRIMARY KEY IDENTITY,
	REC_ID BIGINT NOT NULL,
	PRO_ID BIGINT NOT NULL,
	QUANTITY INT	NOT NULL	DEFAULT(1)	CHECK (QUANTITY>=0),
	PRICE MONEY	NOT NULL	CHECK (PRICE>=0)
 )
 -- Tao rang buoc khoa ngoai
 
ALTER TABLE RECEIPTS  WITH CHECK ADD  CONSTRAINT FK_CUSTOMERS_RECEIPTS 
	FOREIGN KEY(CUS_ID)
		REFERENCES CUSTOMERS (CUS_ID)
ALTER TABLE PRODUCTS  WITH CHECK ADD  CONSTRAINT FK_SUPPLIERS_PRODUCTS 
	FOREIGN KEY(SUP_ID)
		REFERENCES SUPPLIERS (SUP_ID)
ALTER TABLE RECEIPTITEMS  WITH CHECK ADD  CONSTRAINT FK_RECEIPTS_RECEIPTITEMS 
	FOREIGN KEY(REC_ID)
		REFERENCES RECEIPTS (REC_ID)
ALTER TABLE RECEIPTITEMS  WITH CHECK ADD  CONSTRAINT FK_PRODUCTS_RECEIPTITEMS 
	FOREIGN KEY(PRO_ID)
		REFERENCES PRODUCTS (PRO_ID)
ALTER TABLE PRODUCTS 
	Add Constraint AK_Product Unique (PRODUCTCODE);
--go
-- them du lieu vao bang
-- bang SUPPLIERS
INSERT SUPPLIERS VALUES (N'Cty TNHH Rang Dong', N'Tran Hung Dao, District 1', N'083573645')
INSERT SUPPLIERS VALUES (N'Cty Binh Minh', N'Ly Thuong Kiet, District 10 ', NULL)
INSERT SUPPLIERS VALUES (N'Cty TNHH MTV Anh Sang', NULL, NULL)
INSERT SUPPLIERS VALUES (N'Cty TNHH Tuong Lai', NULL, N'0917568473')
INSERT SUPPLIERS VALUES (N'Cty Ban Mai', N'Ky Dong, District 3', NULL)
-- BANG CUSTOMERS
INSERT CUSTOMERS VALUES (N'Le Anh Minh', N'Le Thanh Ton', N'083564652', N'minhla@yahoo.com')
INSERT CUSTOMERS VALUES (N'Tran Anh Khoa', N'Tran Anh Khoa', N'', N'khoata@gmail.com')
INSERT CUSTOMERS VALUES (N'Le Anh Minh', NULL, N'0124574574', N'ngudv@yahoo.com')
INSERT CUSTOMERS VALUES (N'Le Anh Minh', NULL, NULL, N'taidt@gmail.com')
INSERT CUSTOMERS VALUES (N'Le Anh Minh', N'Thong Nhat', N'0124746574', N'nhantn@hotmail.com')
-- BANG PRODUCTS
INSERT PRODUCTS VALUES (N'1', N'P001', N'Samsung Note 4', 17.990)
INSERT PRODUCTS VALUES (N'1', N'P002', N'Asus Zenfone 5', 3.700)
INSERT PRODUCTS VALUES (N'2', N'P003', N'iPhone 4', 8.390)
INSERT PRODUCTS VALUES (N'3', N'P004', N'iPad Mini 3', 9.990)
INSERT PRODUCTS VALUES (N'4', N'P005', N'iPhone 6', 17.790)
-- BANG RECEIPTS
INSERT RECEIPTS VALUES (N'1',N'10-Oct-2017')
INSERT RECEIPTS VALUES (N'1',N'11-Oct-2017')
INSERT RECEIPTS VALUES (N'2',N'15-Oct-2017')
INSERT RECEIPTS VALUES (N'3',N'20-Oct-2017')
INSERT RECEIPTS VALUES (N'5',N'09-Nov-2017')
-- BANG RECEIPTITEMS
INSERT RECEIPTITEMS VALUES (N'1', N'1', N'1', 17.990)
INSERT RECEIPTITEMS VALUES (N'1', N'2', N'1', 3.700)
INSERT RECEIPTITEMS VALUES (N'1', N'3', N'1', 8.390)
INSERT RECEIPTITEMS VALUES (N'2', N'5', N'1', 17.790)
INSERT RECEIPTITEMS VALUES (N'3', N'2', N'2', 3.700)
INSERT RECEIPTITEMS VALUES (N'4', N'2', N'1', 3.700)
INSERT RECEIPTITEMS VALUES (N'4', N'3', N'1', 9.500)
INSERT RECEIPTITEMS VALUES (N'5', N'1', N'1', 19.500)
INSERT RECEIPTITEMS VALUES (N'5', N'3', N'1', 8.390)
INSERT RECEIPTITEMS VALUES (N'5', N'5', N'1', 17.790)
--kiem tra du leu cua cac bang
select * from SUPPLIERS 
select * from CUSTOMERS 
select * from PRODUCTS 
select * from RECEIPTS 
select * from RECEIPTITEMS 